name: Update Slicer Profiles

on:
    schedule:
        -   cron: "0 0 * * *"
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    update_slicer_profiles:
        # Only run on main branch, not on PRs
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup Git
                run: |
                    git config --global user.name "github-actions[bot]"
                    git config --global user.email "github-actions[bot]@users.noreply.github.com"

            -   name: Run update script
                run: |
                    pip install -r requirements.txt
                    python -m ofd script load_profiles

            -   name: Commit changes
                run: |
                    git add .
                    if git commit -m "Update profiles"; then
                        git push origin
                    fi